Invitemembers
castledio/castled pull request #62
Opened 2022-01-18 13:43 UTC by naveenpaul

2022-01-18 14:53 UTC, aruntcet2010 requested changes

2022-01-18 14:53 UTC, aruntcet2010 commented on webapp/app/common/context/sessionContext.tsx
> +        eventService.send({
@naveenpaul @franklinio is it okay to remove this?

2022-01-18 14:53 UTC, aruntcet2010 commented on webapp/app/common/utils/buttonHandler.ts
> +    eventService.send({
same here

2022-01-18 15:08 UTC, franklinio commented on webapp/app/common/context/sessionContext.tsx
> +        eventService.send({
@aruntcet2010 I think an old main was merged back to this branch
@naveenpaul Please pull and rebase your changes to the head of the main.

2022-01-19 03:56 UTC, naveenpaul commented on webapp/app/common/utils/buttonHandler.ts
> +    eventService.send({
@aruntcet2010 we don't need these events to be captured?

2022-01-22 11:00 UTC, closed without merging