improving ui of login and register page
castledio/castled pull request #63
Opened 2022-01-18 14:33 UTC by Vishal-raj-1

2022-01-19 12:30 UTC, mkstayalive commented on webapp/styles/main.scss
> +  background: white;
don't use color names, always use #codes. and that to as scss variables. and all color definitions should go in `light.scss`. talk to naveen

2022-01-19 12:30 UTC, mkstayalive commented on webapp/styles/layout.scss
> +  padding: 23px;
use bootstrap shorthands for padding and margin. like p-3 or p-4 classes

2022-01-19 12:31 UTC, mkstayalive commented on webapp/pages/auth/register.tsx
>          <Button
remove all commented code

2022-01-19 12:32 UTC, mkstayalive commented on webapp/styles/main.scss
> +  font-size: 14px;
use scss variables like $font-size-md

2022-01-20 10:15 UTC, Vishal-raj-1 commented
## Sign In Page:

![signin](https://user-images.githubusercontent.com/59874304/150318903-74d0b124-d562-4de6-91bf-d2368ddd43f5.jpg)

## Sign Up Page:

![signup](https://user-images.githubusercontent.com/59874304/150318910-bee79687-a1ef-4f0a-aa0e-4452a6c0ae2a.jpg)

2022-01-20 11:28 UTC, naveenpaul requested changes
1. Cluster select drop down is not matching design. Please test that it works after changing it to Material design.
2. "to continue to use Castled" text color should have #777777 according to the design
3. All the labels have a different font weight in the design. They're lighter. Try 400/normal. Also the font size is 10px for labels. Is it the same on the code too?
4. On the Sign-up screen, at the bottom of the box, create a link - "Have an account? Sign In". This is not there in the design. But its good to have a sign-in link. On the Login screen, you have the "Create Account" link. Same design and placement.

2022-01-20 11:31 UTC, mkstayalive commented on webapp/styles/main.scss
> +  color: red !important;
use color codes

2022-01-20 11:31 UTC, mkstayalive commented on webapp/styles/main.scss
> +  color: red !important;
also, color definitions should go in light.scss

2022-01-20 20:57 UTC, franklinio commented
@naveenpaul  Wondering if the dark castled logo goes well on the signin page?

2022-01-21 04:23 UTC, mkstayalive commented
@franklinio at the moment we have only light mode. some point later we will support dark mode as well. i think the dark logo will then look good.

2022-02-15 06:38 UTC, closed without merging