pipeline refresh button and change border of error report and run status
castledio/castled pull request #86
Opened 2022-01-24 12:22 UTC by Vishal-raj-1

2022-01-24 12:31 UTC, naveenpaul requested changes
In label - "Processing..." the three dots should be icon class - icon-tabler-dots from https://tablericons.com/ library. And we should get the pulsating animation. Keep the dots size the same as font size.

2022-01-25 10:53 UTC, mkstayalive commented on webapp/styles/main.scss
> +    background-color: #fff8e6;
use scss variables for color codes. All color definitions should go in light.scss.

2022-01-25 10:53 UTC, mkstayalive commented on webapp/styles/main.scss
> +      background-color: #bb9522;
use scss variables for color codes. All color definitions should go in light.scss.

2022-01-25 10:59 UTC, Vishal-raj-1 commented on webapp/styles/main.scss
> +    background-color: #fff8e6;
it's done

2022-01-25 11:00 UTC, Vishal-raj-1 commented on webapp/styles/main.scss
> +      background-color: #bb9522;
Done

2022-02-09 11:11 UTC, Vishal-raj-1 commented
It is solved

2022-02-09 11:11 UTC, closed without merging